### ISSUE TITLE
bta and linux rendering

### ISSUE THREAD

**Issue by Bloxxel64** [SkyDeckAGoGo/bta-issues#100]
**Describe the bug**
Rendering the game is very broken, there can be random lag, the world can disappear, or the game can just crash.

**To Reproduce**
buy an old mac pro
install ubuntu budgie LTS
play bta

**Expected behavior**
not this

**Screenshots**

**Version info (please complete the following information):**
1.7.6_01

**Additional context**
Ubuntu 20.04 focal (x86-64)
5.13.0-30-generic
Intel© Xeon© CPU           W3520  @ 2.67GHz × 4
11.7 GiB
490.4 GB
NVIDIA Corporation G96C [GeForce 9500 GT]

**Crash Logs**
java.lang.NullPointerException
    at ew.f(ChunkCache.java:187)
    at uu.d(Block.java:219)
    at cv.a(RenderBlocks.java:2207)
    at cv.l(RenderBlocks.java:2036)
    at cv.b(RenderBlocks.java:72)
    at dk.a(WorldRenderer.java:150)
    at n.a(RenderGlobal.java:1092)
    at px.a(EntityRenderer.java:569)
    at px.b(EntityRenderer.java:446)
    at net.minecraft.client.Minecraft.run(Minecraft.java:534)
    at java.lang.Thread.run(Thread.java:748)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7f2a940232d0 serial: 30287 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
    at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
    at org.lwjgl.opengl.LinuxKeyboard.nSetDetectableKeyRepeat(Native Method)
    at org.lwjgl.opengl.LinuxKeyboard.setDetectableKeyRepeat(LinuxKeyboard.java:152)
    at org.lwjgl.opengl.LinuxKeyboard.destroy(LinuxKeyboard.java:163)
    at org.lwjgl.opengl.LinuxDisplay.destroyKeyboard(LinuxDisplay.java:1261)
    at org.lwjgl.input.Keyboard.destroy(Keyboard.java:357)
    at net.minecraft.client.Minecraft.d(Minecraft.java:437)
    at net.minecraft.client.Minecraft.run(Minecraft.java:606)
    at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
    at ew.f(ChunkCache.java:187)
    at uu.d(Block.java:219)
    at cv.a(RenderBlocks.java:2207)
    at cv.l(RenderBlocks.java:2036)
    at cv.b(RenderBlocks.java:72)
    at dk.a(WorldRenderer.java:150)
    at n.a(RenderGlobal.java:1092)
    at px.a(EntityRenderer.java:569)
    at px.b(EntityRenderer.java:446)
    at net.minecraft.client.Minecraft.run(Minecraft.java:534)
    at java.lang.Thread.run(Thread.java:748)
Stopping!

**Comment by Joe4422** [comment]
Do you experience the issue on 1.7.6.1?

**Comment by Bloxxel64** [comment]
ill try it

**Comment by Bloxxel64** [comment]
Yay. It's even worse it broke my entire PC

**Comment by SkyDeckAGoGo** [comment]
> Yay. It's even worse it broke my entire PC

What version of java are you using? Can you try on both java 8 and 17 if you can?

**Comment by Bloxxel64** [comment]
8 was what i was using in initally.

so for 1.7.6_01
java 17
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: /home/bloxxel64/.local/share/multimc/instances/Files-MultiMC-1.7.6_01/natives/liblwjgl64.so: /usr/lib/jvm/jdk-17/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/bloxxel64/.local/share/multimc/instances/Files-MultiMC-1.7.6_01/natives/liblwjgl64.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:311)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:283)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(Minecraft.java:99)
	at net.minecraft.client.Minecraft.run(Minecraft.java:455)
	at java.base/java.lang.Thread.run(Thread.java:833)

for java 11
Launching with applet wrapper...
356 recipes
22 achievements
Setting user: Bloxxel64YT, token:<ACCESS TOKEN>:<PROFILE ID>
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.

**Comment by Bloxxel64** [comment]
for 1.7.6.1
java 17
Launching with applet wrapper...
374 recipes
22 achievements
Setting user: Bloxxel64YT, token:<ACCESS TOKEN>:<PROFILE ID>
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/bloxxel64/.local/share/multimc/instances/1.7.6.1-MULTIMC/natives/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: /home/bloxxel64/.local/share/multimc/instances/1.7.6.1-MULTIMC/natives/liblwjgl64.so: /usr/lib/jvm/jdk-17/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/bloxxel64/.local/share/multimc/instances/1.7.6.1-MULTIMC/natives/liblwjgl64.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:311)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:283)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(Minecraft.java:100)
	at net.minecraft.client.Minecraft.run(Minecraft.java:449)
	at java.base/java.lang.Thread.run(Thread.java:833)
Process exited with code 0.

java 11
374 recipes
22 achievements
Setting user: Bloxxel64YT, token:<ACCESS TOKEN>:<PROFILE ID>
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.

**Comment by Bloxxel64** [comment]
Little update for you guys. In the end of the FAQ channel in the modification station server. They have a message detailing how to reduce lag spikes and such. After entering the arguments and setting the minimum and maximum allocated memory to the same value. I found it worked well with the occasional lag Spike. Which I could easily resolved by changing the render distance to reload.

**Comment by Joe4422** [comment]
We'll be including those args in any MultiMC distributions going forward.
