### ISSUE TITLE
Can't screenshot in fullscreen

### ISSUE THREAD

**Issue by yellowwinner** [SkyDeckAGoGo/bta-issues#234]
**Describe the bug**
Normal screenshotting (F2) in fullscreen results an error.

**Screenshots**
![2023-01-07_19 17 03](https://user-images.githubusercontent.com/16910272/211175049-97b5cd28-c97f-492e-a341-7d2e0dc21b26.png)

**Version info (please complete the following information):**
 1.7.6.2_01

**Additional context**
Screenshot attempted at resolution of 2560x1440

**Game log**
```
[19:16:53] [Minecraft main thread] java.lang.IllegalArgumentException: Number of remaining buffer elements is 10513920, must be at least 11059200. Because at most 11059200 elements can be returned, a buffer with at least 11059200 elements is required, regardless of actual returned element count 
[19:16:53] [Minecraft main thread] 	at org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162) 
[19:16:53] [Minecraft main thread] 	at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189) 
[19:16:53] [Minecraft main thread] 	at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:230)
 [19:16:53] [Minecraft main thread] 	at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2450) 
[19:16:53] [Minecraft main thread] 	at net.minecraft.src.ScreenShotHelper.saveScreenshot(ScreenShotHelper.java:42)
 [19:16:53] [Minecraft main thread] 	at net.minecraft.client.Minecraft.screenshotListener(Minecraft.java:759) 
[19:16:53] [Minecraft main thread] 	at net.minecraft.client.Minecraft.run(Minecraft.java:684)
 [19:16:53] [Minecraft main thread] 	at java.lang.Thread.run(Unknown Source)
[19:16:53] [Minecraft main thread] [CHAT] Failed to save: java.lang.IllegalArgumentException: Number of remaining buffer elements is 10513920, must be at least 11059200. Because at most 11059200 elements can be returned, a buffer with at least 11059200 elements is required, regardless of actual returned element count 
[19:16:53] [Minecraft main thread] [CHAT] Failed to save: java.lang.IllegalArgumentException: Number of r
 [19:16:53] [Minecraft main thread] [CHAT] emaining buffer elements is 10513920, must be at least 110592 
[19:16:53] [Minecraft main thread] [CHAT] 00. Because at most 11059200 elements can be returned, a buf 
[19:16:53] [Minecraft main thread] [CHAT] fer with at least 11059200 elements is required, regardless of
```

**Comment by yellowwinner** [comment]
Additionally, the same issue applies with Photo Mode.

```
[21:52:25] [Minecraft main thread] ########## GL ERROR ##########
[21:52:25] [Minecraft main thread] @ Pre render
[21:52:25] [Minecraft main thread] 1281: Invalid value
[21:52:25] [Minecraft main thread] Setup Framebuffer: 2560 x 1440
[21:52:27] [Minecraft main thread] java.lang.IllegalArgumentException: Number of remaining buffer elements is 10513920, must be at least 11059200. Because at most 11059200 elements can be returned, a buffer with at least 11059200 elements is required, regardless of actual returned element count
[21:52:27] [Minecraft main thread] 	at org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162)
[21:52:27] [Minecraft main thread] 	at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189)
[21:52:27] [Minecraft main thread] 	at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:230)
[21:52:27] [Minecraft main thread] 	at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2450)
[21:52:27] [Minecraft main thread] 	at net.minecraft.src.ScreenShotHelper.saveScreenshot(ScreenShotHelper.java:42)
[21:52:27] [Minecraft main thread] 	at net.minecraft.src.GuiPhotoMode.drawScreen(GuiPhotoMode.java:236)
[21:52:27] [Minecraft main thread] 	at net.minecraft.src.EntityRenderer.updateCameraAndRender(EntityRenderer.java:536)
[21:52:27] [Minecraft main thread] 	at net.minecraft.client.Minecraft.run(Minecraft.java:661)
[21:52:27] [Minecraft main thread] 	at java.lang.Thread.run(Unknown Source)
```

**Comment by pedrothepanda64** [comment]
Try updating to 1.7.6.2_02, the latest version.
