### ISSUE TITLE
Linux Rendering is broken

### ISSUE THREAD

**Issue by Bloxxel64** [SkyDeckAGoGo/bta-issues#99]
[2:17 PM]
java.lang.NullPointerException
    at ew.f(ChunkCache.java:187)
    at uu.d(Block.java:219)
    at cv.a(RenderBlocks.java:2207)
    at cv.l(RenderBlocks.java:2036)
    at cv.b(RenderBlocks.java:72)
    at dk.a(WorldRenderer.java:150)
    at n.a(RenderGlobal.java:1092)
    at px.a(EntityRenderer.java:569)
    at px.b(EntityRenderer.java:446)
    at net.minecraft.client.Minecraft.run(Minecraft.java:534)
    at java.lang.Thread.run(Thread.java:748)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7f2a940232d0 serial: 30287 error: BadWindow (invalid Window parameter) request_code: 2 minor_code: 0
    at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
    at org.lwjgl.opengl.LinuxKeyboard.nSetDetectableKeyRepeat(Native Method)
    at org.lwjgl.opengl.LinuxKeyboard.setDetectableKeyRepeat(LinuxKeyboard.java:152)
    at org.lwjgl.opengl.LinuxKeyboard.destroy(LinuxKeyboard.java:163)
    at org.lwjgl.opengl.LinuxDisplay.destroyKeyboard(LinuxDisplay.java:1261)
    at org.lwjgl.input.Keyboard.destroy(Keyboard.java:357)
    at net.minecraft.client.Minecraft.d(Minecraft.java:437)
    at net.minecraft.client.Minecraft.run(Minecraft.java:606)
    at java.lang.Thread.run(Thread.java:748)
[2:21 PM]
java.lang.NullPointerException
    at ew.f(ChunkCache.java:187)
    at uu.d(Block.java:219)
    at cv.a(RenderBlocks.java:2207)
    at cv.l(RenderBlocks.java:2036)
    at cv.b(RenderBlocks.java:72)
    at dk.a(WorldRenderer.java:150)
    at n.a(RenderGlobal.java:1092)
    at px.a(EntityRenderer.java:569)
    at px.b(EntityRenderer.java:446)
    at net.minecraft.client.Minecraft.run(Minecraft.java:534)
    at java.lang.Thread.run(Thread.java:748)
Stopping!

**Comment by Joe4422** [comment]
Please use the template provided to submit bug reports; we need more information.
